# Farming Abilities Configuration

abilities:
  # Green Thumb ability
  greenthumb:
    enabled: true
    unlock-level: 10
    name: "&aGreen Thumb"
    description: "Chance to automatically replant harvested crops"
    effects:
      # Format: level: chance (0.0 - 1.0)
      10: 0.10  # 10% at level 10
      20: 0.20  # 20% at level 20
      30: 0.30  # 30% at level 30
      40: 0.40  # 40% at level 40
      50: 0.50  # 50% at level 50
      60: 0.60  # 60% at level 60
    messages:
      activate: "&aYour Green Thumb ability automatically replanted the crop!"

  # Bountiful Harvest ability
  bountifulharvest:
    enabled: true
    unlock-level: 30
    name: "&eHarvest"
    description: "Chance for additional drops when harvesting crops"
    effects:
      # Format: level: chance (0.0 - 1.0)
      30: 0.10  # 10% at level 30
      40: 0.20  # 20% at level 40
      50: 0.30  # 30% at level 50
      60: 0.40  # 40% at level 60
      70: 0.50  # 50% at level 70
      80: 0.60  # 60% at level 80
    messages:
      activate: "&aYour Bountiful Harvest ability gave you extra crops!"

  # Nature's Blessing ability
  naturesblessing:
    enabled: true
    unlock-level: 50
    name: "&dNature's Blessing"
    description: "Chance for instant crop growth when planting"
    effects:
      # Format: level: chance (0.0 - 1.0)
      50: 0.05  # 5% at level 50
      60: 0.10  # 10% at level 60
      70: 0.15  # 15% at level 70
      80: 0.20  # 20% at level 80
      90: 0.25  # 25% at level 90
      100: 0.30  # 30% at level 100
    messages:
      activate: "&aYour Nature's Blessing ability instantly grew your crop!"